<a href="https://colab.research.google.com/github/du6293/project/blob/main/%EC%8B%AC%ED%99%945_numpy_%EC%8B%A4%EC%8A%B5VI_%EC%99%84%EC%84%B1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 실습 I


####1 : 다차원 배열 생성하기(난이도 : 중)

대각 성분이 모두 10인 4x4 크기의 다차원 배열을 생성하여라.






In [ ]:
import numpy as np

np.eye(4) *10

array([[10.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 10.]])

####2 : 
sin0도에서 sin180도 사이의 값 11개를 다음과 같이 출력하여라. 이때 sin() 함수의 입력을 라디안을 사용하여라( 힌트 linspace()함수를 사용해조가. 라디안으로 180도는 np.pi 사용하면 된다.)

In [ ]:
np.linspace(0,np.sin(np.pi), 11)

array([0.00000000e+00, 1.22464680e-17, 2.44929360e-17, 3.67394040e-17,
       4.89858720e-17, 6.12323400e-17, 7.34788079e-17, 8.57252759e-17,
       9.79717439e-17, 1.10218212e-16, 1.22464680e-16])

###3(난이도 : 하)

b = np.array([[1, 1], [2, 2], [3, 3]])

위의 b 배열에 insert(b, 1, [1, 2, 3], axis=1)을 수행하고 그 결과를 출력하여라. 



In [ ]:
b = np.array([[1,1],[2,2],[3,3]])
b
np.insert(b, 1, [1,2,3], axis = 1)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

### 4(난이도 : 중)
 d 배열의 값이 axis 1, axis 0 방향에 대하여 각각 내림차순 정렬이 되도록 하고 그 결과를 출력하여라(힌트: 넘파이의 flip() 함수를 사용해보자).


```
d= array([[35, 24, 55],
       [69, 19,  9],
       [ 4,  1, 11]])

array([[55, 35, 24],
       [69, 19,  9],
       [11,  4,  1]])

       
array([[69, 24, 55],
       [35, 19, 11],
       [ 4,  1,  9]])

```







In [ ]:
d = np.array([[35,24,55],[69,19,9],[4,1,11]])
d

array([[35, 24, 55],
       [69, 19,  9],
       [ 4,  1, 11]])

In [ ]:
d.sort()
np.flip(d, axis=1)

array([[55, 35, 24],
       [69, 19,  9],
       [11,  4,  1]])

In [ ]:
d.sort(axis=0)
np.flip(d, axis=0)

array([[69, 24, 55],
       [35, 19, 11],
       [ 4,  1,  9]])


### 5 : 다차원 행렬의 생성과 활용(난이도 : 중)

1. 1에서 9까지의 모든 정수 값을 크기 순서대로 가지는 3x3 크기의 행렬 a를 arange()와 reshape()을 이용하여 생성하고, 모든 성분의 값이 3인 3x3 크기의 행렬 b를 full() 함수를 사용하여 생성한 다음, 다음과 같이 출력하여라.

a = [[1 2 3] 
     [4 5 6]
     [7 8 9]]


b = [[3 3 3] 
     [3 3 3]
     [3 3 3]]


2. 다음과 같은 행렬 연산의 수행한 후 그 결과를 출력하시오.

      a + b, a - b, a * b, a / b, a @ b, a ** 2






In [ ]:
a = np.arange(1, 10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b = np.full((3,3), 3)
b

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [ ]:
print('a+b=',a+b)
print('a-b=',a-b)
print('a*b=',a*b)
print('a/b=',a/b)
print('a@b=',a@b)
print('a**2=',a**2)

a+b= [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
a-b= [[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]
a*b= [[ 3  6  9]
 [12 15 18]
 [21 24 27]]
a/b= [[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]
a@b= [[18 18 18]
 [45 45 45]
 [72 72 72]]
a**2= [[ 1  4  9]
 [16 25 36]
 [49 64 81]]



### 6(난이도 : 중)
arange()를 사용하여 1에서 50까지의 원소를 가지는 다차원 배열을 만들자. 이 배열의 원소 50개를 랜덤하게 섞은 후 80%의 데이터는 train_data에 넣고 나머지 20%의 데이터는 test_data라는 배열에 넣어서 이 두 배열을 반환하는 함수 train_test_split()을 만들자. 반환된 배열값을 각각 출력해 보자.



In [ ]:
a = np.arange(1, 51)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
np.random.shuffle(a)
a

array([ 5, 15, 31, 24, 12, 14, 42, 47,  8, 36, 19, 38, 10, 44, 40, 39, 28,
       34, 48,  3, 41, 35, 49, 29, 43, 11, 17,  1, 22, 18, 33, 20, 16, 30,
        2, 23, 45, 21,  4, 13, 32,  9,  7, 27,  6, 25, 50, 37, 26, 46])

In [ ]:
a = np.arange(1, 51)
np.random.shuffle(a)

def train_test_split(data,per):
  n = len(data) *per//100
  train = data[0:n]
  test = data[n:]
  return train, test

train_data, test_date = train_test_split(a,80) 
print(train_data, test_date)


[ 4  6 12 10 42 37 38 29 33  9  1  3 49 45 30 11 32  2 40  5 20 17 41 50
 25 44 19 26 23  8 16 48 14  7 27 13 34 35 24 28] [15 31 36 22 18 43 47 21 46 39]


### 7 다차원 행렬의 생성과 활용 (난이도 : 중)

1) 다음과 같은 연립방정식의 해를 numpy.linalg의 solve()함수를 사용하여 구하여라.


```
x + y -z = 0
2x - y +3z = 9
x + 2y +z = 8
```



In [ ]:
a = np.array([[1,1,-1], [2,-1, 3],[1,2,1]])
b = np.array([0,9,8])
x = np.linalg.solve(a, b)
x

array([1., 2., 3.])

2) 1번 문제의 연립방정식은 다음과 같은 행렬 를 가진다.

```
A = np.array([[1,1,-1],[2,-1, 3],[1,2,1]],dtype='int32')
```
이 행렬의 행렬식을 linalg.det()함수를 사용하여 다음과 같이 구하여라


```
det(A) = -11.0
```




In [ ]:
np.linalg.det(a)

-11.000000000000002

# 실습II

###1 다음의 기능을 넘파이를 사용하여 구현하시오. 
1) numpy의 arange() 함수를 사용하여 1에서 45까지의 연속적인 번호를 생성하여라. 

In [ ]:
a = np.arange(1, 46)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

2) 랜덤 씨드 값은 85로 설정하여라. 그런 다음 이 배열을 랜덤하게 섞어서(shuffle) 첫 6개의 숫자를 슬라이싱 하라. 그 결과를 lotto라는 변수에 할당한 후, 다음과 같이 출력하라.


In [ ]:
np.random.seed(85)
np.random.shuffle(a)
a

array([35, 21,  6, 33, 38, 34,  9, 25, 29, 45,  3, 12,  5, 24, 37, 40, 15,
       17, 20, 42, 23, 30, 11, 41,  8, 26, 36, 22, 18,  2, 31, 10,  1, 44,
        7, 27,  4, 19, 16, 13, 43, 39, 32, 28, 14])

In [ ]:
lotto =a[0:6]
print(lotto)

[35 21  6 33 38 34]


3) lotto 배열을 정렬한 후 출력하고 추가번호를 출력하라. 추가 번호는 7번째 숫자를 출력하라.

In [ ]:
a[6]

9

4) 다음과 같이 0에서 24까지의 값을 가지는 5x5 크기의 2차원 행렬 n_arr을 생성하여라.

In [ ]:
n_arr = np.arange(0, 25).reshape(5,5)
n_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

5) 앞서 만든 n_arr의 가장 첫 원소와 가장 마지막 원소를 인덱싱하여 다음과 같이 출력하여라. 이 떄, 마지막 원소의 인덱싱은 반드시 음수 값을 사용하여라.

In [ ]:
print(f'첫원소: {n_arr[0,0]}, 마지막 원소: {n_arr[-1,-1]}')

첫원소: 0, 마지막 원소: 24


6) n_arr 배열에 슬라이싱을 적용하여 다음과 같은 값을 가지는 배열을 생성하여라.


```
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
```



In [ ]:
n_arr[:2, :]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

7) n_arr 배열에 슬라이싱을 적용하여 다음과 같은 값을 가지는 배열을 생성하여라.


```
array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])
```



In [ ]:
n_arr[:, ::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

8) n_arr 배열에 슬라이싱을 적용한 후, reshape()을 적용하여 다음과 같은 값을 가지는 배열을 생성하여라



```
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])
```



In [ ]:
n_arr
n_arr[:2, :].reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

##2 다음과 같이 난수로 이루어진 2x2x2 형태의 배열 a를 생성하여라.


```
array([[[ 0.19066621, -0.23387768],
        [ 0.39469745, -0.34461204]],

       [[-1.11862745,  1.62978122],
        [ 0.46794657, -0.06532543]]])
```



In [ ]:
a = np.random.randn(8).reshape(2,2,2)
a

array([[[-0.7889257 ,  2.58304684],
        [ 0.51096797, -0.09249755]],

       [[ 1.21599711,  1.29370903],
        [-1.03238097,  0.78078012]]])

1) a 배열에서 max() 메소드를 사용하여 가장 큰 값을 구하여 다음과 같이 출력하여라.

In [ ]:
a.max()

2.5830468423246535

2) a 배열에서 min() 메소드를 사용하여 가장 작은 값을 구한 다음 출력하여라.

In [ ]:
a.min()

-1.0323809679898892