<a href="https://colab.research.google.com/github/du6293/project/blob/main/%EC%8B%AC%ED%99%945_numpy_%EC%99%84%EC%84%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy import 및 속성

In [ ]:
import numpy as np


배열의 속성

In [ ]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
print('type: ',type(a))
print('dtype: ',a.dtype)
print('ndim: ',a.ndim)
print('shape: ',a.shape)
print('size: ',a.size)
print('itemsize: ',a.itemsize)

type:  <class 'numpy.ndarray'>
dtype:  int64
ndim:  1
shape:  (4,)
size:  4
itemsize:  8


# Numpy 배열의 생성

##array 함수를 사용하여 생성

In [ ]:
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [ ]:
a1.shape

(5,)

In [ ]:
a2 = np.array([[1,2],[3,4]])
a2

array([[1, 2],
       [3, 4]])

In [ ]:
a2.shape

(2, 2)

In [ ]:
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
a3.shape

(2, 2, 2)

## arange()와 reshape()함수을 사용하여 생성

In [ ]:
a1 = np.arange(0,12)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a1.shape

(12,)

In [ ]:
a2 = a1.reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#음수는 나머지 원소를 계산해서 해당 차원크기를 자동으로 맞춤
a3 = a1.reshape(3,-1)
a3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a4 = np.arange(36,dtype=float).reshape(3,4,3)
a4

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]],

       [[24., 25., 26.],
        [27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

## 다양한 함수로 numpy 내장함수를 사용하여 생성

In [ ]:
#linspace 균등한게 갯수만큼 생성
a = np.linspace(0, 1, 6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
#zeros 0으로 채우는 행렬
a2 = np.zeros(3, dtype='int64')
a2

array([0, 0, 0])

In [ ]:
a2 = np.zeros((3,3), dtype='int64')
a2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
#ones
a3 = np.ones(2, dtype='int64')
a3

array([1, 1])

In [ ]:
#ones 1로 채우는 행렬
a3 = np.ones((5,5), dtype='int64')
a3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
#full 지정한 값으로 채우는 행렬
a4 = np.full((3,3),3)
a4

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [ ]:
a4.dtype

dtype('int64')

정방행렬: 행와 열의 갯수같은 행령
단위행렬: 대각선 원소는 1이고 나머진 0인 행렬 

In [ ]:
#identity 정방단위행렬
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#diag 대각선 배열 생성 및 추출
a = np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
a = np.arange(9).reshape(3,3)
a


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.diag(a)

array([0, 4, 8])

In [ ]:
#eye 대각선 1, 나머지 0인 2차원 행렬 꼭 정방행렬 아님
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a = np.eye(2,3)
a

array([[1., 0., 0.],
       [0., 1., 0.]])

***likes()함수로 배열생성

In [ ]:
#zeros_like() 
a = np. arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.zeros_like(a) 

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones_like(a) 

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.full_like(a,7) 

array([[7, 7, 7],
       [7, 7, 7]])

Random 서브 패키지를 사용하여 생성

In [ ]:
#0~1사이의 균일한 확률분포로 실수 난수 발생
np.random.rand(5)

array([0.76354928, 0.6812732 , 0.86797848, 0.6887304 , 0.07430498])

In [ ]:
#표준정규분포의 난수 추출, 평균0, 분산 1
rnd = np.random.randn(7)
rnd
rnd.round(2)

array([ 0.85, -0.97,  1.23,  1.46, -1.41, -0.59,  0.19])

In [ ]:
#평균 165, 표준편차 10
rnd = np.random.randn(7) *10 + 165
rnd
rnd.astype(int)

array([166, 175, 169, 179, 181, 170, 162])

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(a)
a

array([6, 5, 7, 1, 8, 0, 4, 9, 2, 3])

In [ ]:
np.random.randint(1, 100, size=10) #끝값이 안들어감

array([57,  7, 58, 67, 22, 86,  4, 95, 15, 31])

#실습I

1.  0에서 9까지의 정수값을 가지는 ndarray 객체a를 넘파이를 이용하여 작성하여 다음과 같이 출력하세요

```
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```






In [ ]:
a= np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. range()함수를 사용하여 0에서 9까지의 정수 값을 가지는 ndarray 객체 b를 만들고 문제 1의 결과와 같이 나타내도록 하세요.

In [ ]:
b= np.array(range(10))
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. 문제 2의 코드를 수정하여 0에서 9까지의 정수 값 중에서 다음과 같이 짝수를 가지는 ndarray 객체 c를 출력하세요.


```
array([0, 2, 4, 6, 8])
```



In [ ]:
c = np.array(range(0,10,2))
c

array([0, 2, 4, 6, 8])

4. 문제 3번 ndarray 객체 c의 shape, ndim, dtype, size. itemsize를 다음과 같이 출력하세요.

In [ ]:
print(f'c.shape = {c.shape}')
print(f'c.ndim = {c.ndim}')
print(f'c.dtype = {c.dtype}')
print(f'c.size = {c.size}')
print(f'c.itemsize = {c.itemsize}')

c.shape = (5,)
c.ndim = 1
c.dtype = int64
c.size = 5
c.itemsize = 8


5. full() 함수를 이용하여 모든 원소의 값이 2인 3x3 배열 a1을 생성하세요.
```
a1 = [[2 2 2]
      [2 2 2]
      [2 2 2]]
```

In [ ]:
a1 = np.full((3,3),2)
a1

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

6. arange() 함수를 사용하여 1에서 12까지 12개의 원소를 가지는 1차원 배열 a2를 생성하세요.

```
a2 = [ 1 2 3 4 5 6 7 8 9 10 11 12]
```

In [ ]:
a2 = np.arange(1, 13)
print('a2 = ',a2)

a2 =  [ 1  2  3  4  5  6  7  8  9 10 11 12]


7. arange() 함수의 step 값을 이용하여 1에서 50까지 정수 중에서 3의 배수만을 가지는 배열 a3을 생성하세요.

```
a3 = [ 3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48]
```


In [ ]:
a3 = np.arange(3, 50, 3)
a3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

8. 0에서 20 사이에서 동일한 간격의 값을 가지는 원소 5개를 가진 a4 배열을 생성하세요.

```
a4 = [ 0. 5. 10. 15. 20.]
```

In [ ]:
a4 = np.linspace(0 ,20, 5)
a4

array([ 0.,  5., 10., 15., 20.])

# Numpy 배열 연산

## 사칙연산 element wise

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [ ]:
#덧셈
print('a+b=',a+b)
print('a+b=',np.add(a,b))
#뺄셈
print('a-b=',a-b)
print('a-b=',np.subtract(a,b))
#곱셈
print('a*b=',a*b)
print('a*b=',np.multiply(a,b))
#나숫셈
print('a/b=',a/b)
print('a/b=',np.divide(a,b))
#거듭제곱
print('a**b=',a**b)
print('a**b=',np.power(a,b))

a+b= [ 6  8 10 12]
a+b= [ 6  8 10 12]
a-b= [-4 -4 -4 -4]
a-b= [-4 -4 -4 -4]
a*b= [ 5 12 21 32]
a*b= [ 5 12 21 32]
a/b= [0.2        0.33333333 0.42857143 0.5       ]
a/b= [0.2        0.33333333 0.42857143 0.5       ]
a**b= [    1    64  2187 65536]
a**b= [    1    64  2187 65536]


In [ ]:
a1 = np.array([[1,2],[3,4]])
a2= np.array([[5,6],[7,8]])
print(a1)
print(a2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
a1 + a2

array([[ 6,  8],
       [10, 12]])

In [ ]:
#배열의 곱셈
np.multiply(a1, a2) # a1 * a2 

array([[ 5, 12],
       [21, 32]])

In [ ]:
#행렬의 곱셈
np.matmul(a1, a2) # a1 @ a2 

array([[19, 22],
       [43, 50]])

## 브로드캐스팅

In [ ]:
a = np.array([1,2,3,4])
a + 1

array([2, 3, 4, 5])

In [ ]:
a*3

array([ 3,  6,  9, 12])

In [ ]:
b = np.zeros((2,2,4))
b

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
a+b

array([[[1., 2., 3., 4.],
        [1., 2., 3., 4.]],

       [[1., 2., 3., 4.],
        [1., 2., 3., 4.]]])

In [ ]:
a = np.arange(0, 40, 10).reshape(4,1)
a

array([[ 0],
       [10],
       [20],
       [30]])

In [ ]:
b = np. arange(0,3)
b

array([0, 1, 2])

In [ ]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

# 실습II

1. 1에서 9까지의 모든 정수 값을 크기 순서대로 가지는 3x3 크기의 행렬 a를 생성하고, 모든 성분의 값이 2인 3x3 크기의 행렬 b를 생성하여라.


```
a= [[1 2 3]  
 [4 5 6]
 [7 8 9]]

 b= [[2 2 2]
 [2 2 2]
 [2 2 2]]
```



In [ ]:
a = np.arange(1,10).reshape(3,3)
print('a=',a)

a= [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
b = np.full((3,3),2)
print('b=', b)

b= [[2 2 2]
 [2 2 2]
 [2 2 2]]


2. 다음 행렬 연산의 결과를 예상한 후 실행하고 그 결과를 적으세요.

In [ ]:
a + b

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a - b


array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [ ]:
a * b


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
a / b


array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [ ]:
a @ b


array([[12, 12, 12],
       [30, 30, 30],
       [48, 48, 48]])

In [ ]:
a ** b


array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

# 배열의 결합

concatenate():기존 축(차원)에 따라 결합
stack() 새로운 축(차원)에 따라 결합, hstack(), vstack(), dstack()

In [ ]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
np.concatenate((a1, a2), axis = 0)

array([1, 2, 3, 4, 5, 6])

In [ ]:
a1 = np.array([[1,2],[3,4]])
a1

array([[1, 2],
       [3, 4]])

In [ ]:
a2 = np.array([[5,6],[7,8]])
a2

array([[5, 6],
       [7, 8]])

In [ ]:
np.concatenate((a1, a2), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
a = np.stack((a1, a2))
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
a.shape

(2, 2, 2)

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
np.hstack([a*10, a*20])

array([ 0, 10, 20, 30, 40,  0, 20, 40, 60, 80])

In [ ]:
np.vstack([a*10, a*20])

array([[ 0, 10, 20, 30, 40],
       [ 0, 20, 40, 60, 80]])

In [ ]:
a = np.dstack([a*10, a*20])
a

array([[[   0,    0,    0,    0],
        [ 100,  200,  200,  400],
        [ 200,  400,  400,  800],
        [ 300,  600,  600, 1200],
        [ 400,  800,  800, 1600]]])

In [ ]:
a.shape

(1, 5, 4)

# 배열의 분리

In [ ]:
a = np.arange(1, 25).reshape(4,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
#hsplit 수평축 - 열방향
np.hsplit(a,2)

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21]]), array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24]])]

In [ ]:
#vsplit 수직축 -행방향
np.vsplit(a,2)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])]

In [ ]:
np.hsplit(a,3)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]]), array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22]]), array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24]])]

In [ ]:
np.vsplit(a,3)

ValueError: ignored

In [ ]:
np.vsplit(a,4)

[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24]])]

# 형태변환

reshape

In [ ]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
a= np.arange(20).reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

전치ㅣ

In [ ]:
#전치 T 행과열이 바뀜, a.T
a.transpose()

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [ ]:
a.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

평탄화 1차원으로 바꿈

In [ ]:
f = a.flatten() #복사
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
a[0]= 30
a

array([[30, 30, 30, 30],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
r= a.ravel() # 원래 배열 수정
r

array([30, 30, 30, 30,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
a[1] = 20
a


array([[30, 30, 30, 30],
       [20, 20, 20, 20],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
r

array([30, 30, 30, 30, 20, 20, 20, 20,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# 실습III

1. arange() 함수를 사용하여 1에서 12까지의 원소를 가지는 1차원 배열 a1을 생성하여라. 그리고 이 a1 배열을 reshape() 메소드를 사용하여 2행 6열의 행렬로 재구성하세요.

```
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])
```



In [ ]:
a1 = np.arange(1, 13).reshape(2,6)
a1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

2. arange() 함수를 사용하여 1에서 30까지의 원소를 가지는 1차원
배열 a2을 생성하여라. 그리고 이 a2 배열을 reshape() 메소드를 사용하여 3행 10열의 행렬로 재구성하세요


```
array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])
```



In [ ]:
a2 = np.arange(1, 31).reshape(3, 10)
a2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

3. 문제 2에서 생성한 a2 배열을 reshape() 메소드를 사용하여 6행 5열의 행렬로 재구성한 행렬 a3을 생성하세요.


```
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])
```



In [ ]:
a3 = a2.reshape(6,5)
a3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

4. 문제 3에서 생성한 a3 배열을 transpose() 함수를 사용하여 다음과 같은 전치 행렬을 생성하여라

In [ ]:
a3.T

array([[ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29],
       [ 5, 10, 15, 20, 25, 30]])

# 배열 비교

In [ ]:
a1 = np.array([1,2,3,4])
a2 = np.array([3,2,5,4])

a1 == a2

array([False,  True, False,  True])

In [ ]:
a1> a2

array([False, False, False, False])

In [ ]:
np.array_equal(a1, a2)

False

In [ ]:
a3 = np.array([1,2,3,4])
np.array_equal(a1, a3)

True

# 배열 정렬

In [ ]:
a = np.array([4,2,6,5,1,3,0])
a

array([4, 2, 6, 5, 1, 3, 0])

In [ ]:
np.sort(a) #원래 배열을 수정하지 않고 view

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
a


array([4, 2, 6, 5, 1, 3, 0])

In [ ]:
a.sort() #배열자체가 정렬됨
a

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
np.sort(a)[::-1]

array([6, 5, 4, 3, 2, 1, 0])

축을 지정하여 정렬

In [ ]:
a = np.array([[2,1,6],
              [0,7,4],
              [5,3,2]])
a


array([[2, 1, 6],
       [0, 7, 4],
       [5, 3, 2]])

In [ ]:
a.shape

(3, 3)

In [ ]:
np.sort(a, axis=0)

array([[0, 1, 2],
       [2, 3, 4],
       [5, 7, 6]])

In [ ]:
np.sort(a, axis=1)

array([[1, 2, 6],
       [0, 4, 7],
       [2, 3, 5]])

# 배열의 축
인덱스를 기술하는 순서 축에 따라 계산

In [ ]:
a = np.arange(0,6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
a.sum()

15

In [ ]:
a.sum(axis=0) # 열끼리 더함

array([6, 9])

In [ ]:
a.sum(axis=1)  # 행끼리 더함

array([1, 5, 9])

In [ ]:
print('min',a.min())
print('max',a.max())

min 0
max 5


In [ ]:
print('axis =0, min',a.min(axis =0))
print('axis =0, max',a.max(axis =0))

axis =0, min [0 1]
axis =0, max [4 5]


# 새로운 요소의 삽입

In [ ]:
a = np.array([1,3,4])
np.insert(a, 1, 2)

array([1, 2, 3, 4])

In [ ]:
a = np.array([[1,1],[2,2],[3,3]])
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [ ]:
np.insert(a, 1, 4, axis =0 )

array([[1, 1],
       [4, 4],
       [2, 2],
       [3, 3]])

In [ ]:
np.insert(a, 1, 4, axis =1 )

array([[1, 4, 1],
       [2, 4, 2],
       [3, 4, 3]])

# 실습IV

1. 1에서 100까지의 랜덤 정수 15개를 np.random.randint()를 통해서 생성하여라. 이렇게 생성한 정수 값들을 (3, 5)의 shape을 가지는 행렬 a에 저장하도록 하여 출력하세요.

In [ ]:
a = np.random.randint(1, 101, size=15).reshape(3,5)
a

array([[26, 86,  2, 11, 39],
       [ 1, 58, 43, 81, 40],
       [35, 37, 59, 50, 88]])

2. 문제 1에서 생성한 a 행렬에 대해 열방향의 최댓값, 최솟값, 평균을 각각 다음과 같이 출력하세요.

In [ ]:
print('a 열방향 최댓값: ', a.max(axis=0))
print('a 열방향 최소값: ', a.min(axis=0))
print('a 열방향 평균: ', a.mean(axis=0))

a 열방향 최댓값:  [35 86 59 81 88]
a 열방향 최소값:  [ 1 37  2 11 39]
a 열방향 평균:  [20.66666667 60.33333333 34.66666667 47.33333333 55.66666667]


3. 문제 1에서 생성한 a 행렬에 대해 행방향의 최댓값, 최솟값, 평균을 각각 다음과 같이 출력하세요.

In [ ]:
print('a 열방향 최댓값: ', a.max(axis=1))
print('a 열방향 최소값: ', a.min(axis=1))
print('a 열방향 평균: ', a.mean(axis=1))

a 열방향 최댓값:  [86 81 88]
a 열방향 최소값:  [ 2  1 35]
a 열방향 평균:  [32.8 44.6 53.8]


# 배열의 인덱싱과 슬라이싱

## 1차원 배열의 인덱싱과 슬라이싱

In [ ]:
a = np.array([1,2,3])
print(a[0], a[1], a[2])

1 2 3


In [ ]:
print(a[-1], a[-2], a[-3])

3 2 1


In [ ]:
print(a[np.array([0,1])]) #a[0,1]
print(a[np.array([0,2])]) #a[0,3]
print(a[np.array([1,1,1])]) #a[1,1,1]

[1 2]
[1 3]
[2 2 2]


In [ ]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])
a[1:5]

array([20, 30, 40, 50])

In [ ]:
a[1:]

array([20, 30, 40, 50, 60, 70, 80])

In [ ]:
a[:]

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
a[::2]

array([10, 30, 50, 70])

## 다차원 배열의 인덱싱과 슬라이싱

In [ ]:
a = np.arange(0,6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
print(a[0,0])  # 0행 0열
print(a[0,1])  # 0행 1열
print(a[2,1])  # 2행 1열

0
1
5


In [ ]:
a[[0,1],[1,1]]

array([1, 3])

In [ ]:
a[a>2]

array([3, 4, 5])

In [ ]:
a = np.arange(0, 9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a[0]

array([0, 1, 2])

In [ ]:
a[0,:]

array([0, 1, 2])

In [ ]:
a[:,0]

array([0, 3, 6])

In [ ]:
a[0,0:2]

array([0, 1])

In [ ]:
a[0:2, 0:2]  # 0~1행 0~1열

array([[0, 1],
       [3, 4]])

In [ ]:
a[1:, 1:]

array([[4, 5],
       [7, 8]])

In [ ]:
a[1:, 1:].shape

(2, 2)

In [ ]:
a = np.arange(0, 24).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
a[1,2,1]

11

In [ ]:
a[0]

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
a[0,0]

array([0, 1])

In [ ]:
a[0,2]

array([4, 5])

In [ ]:
np.concatenate((a[0,0],a[0,2]),axis=0)

array([0, 1, 4, 5])

In [ ]:
a = np.arange(1, 17).reshape(4,-1)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
a % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [ ]:
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

# 실습V

*1*. 0에서 15까지의 연속적인 값을 원소로 가지는 4x4 크기의 2차원 배열 a를 생성하여라. 이 a를 인덱싱하여 다음과 같은 b, c, d, e, f 배열을 구하세요.


```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])
```


```
b= [ 1  5  9 13]
c= [ 9 10 11]
d= [[0 1]
 [4 5]]
e= [[ 5  6]
 [ 9 10]]
```




In [ ]:
a = np.arange(0, 16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
b = a[:, 1]
print('b=',b )

b= [ 1  5  9 13]


In [ ]:
c = a[2, 1:]
print('c=',c)

c= [ 9 10 11]


In [ ]:
d = a[0:2, 0:2]
print('d=',d)

d= [[0 1]
 [4 5]]


In [ ]:
e = a[1:3, 1:3]
print('e=',e)

e= [[ 5  6]
 [ 9 10]]


2. 문제 1에서 생성한 배열 a를 슬라이싱하고 평탄화 연산을 하여 다음과 같은 배열 f, g, h를 생성하세요.


```
f= [0 1 2 4 5 6]
g= [ 8  9 10 11 12 13 14 15]
h= [ 5  6  7 13 14 15]
```



In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
f = a[0:2, 0:3].flatten()
print('f=',f)

f= [0 1 2 4 5 6]


In [ ]:
g = a[2:, :].flatten()
print('g=',g)


g= [ 8  9 10 11 12 13 14 15]


In [ ]:
a1 = a[1, 1:]
print(a1)
a2 = a[3, 1:]
print(a2)

[5 6 7]
[13 14 15]


In [ ]:
h = np.concatenate((a1, a2))
print('h=',h)

h= [ 5  6  7 13 14 15]


3. 3차원 배열을 다음과 같이 인덱스와 원소 값이 나타나도록 출력하세요.(힌트 : for 문과 ndindex(a.shape) 함수를 사용)



```
array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])
```



```
index        element
(0, 0, 0)      0
(0, 0, 1)      1
(0, 1, 0)      2
(0, 1, 1)      3
(0, 2, 0)      4
(0, 2, 1)      5
(1, 0, 0)      6
(1, 0, 1)      7
(1, 1, 0)      8
(1, 1, 1)      9
(1, 2, 0)     10
(1, 2, 1)     11
(2, 0, 0)     12
(2, 0, 1)     13
(2, 1, 0)     14
(2, 1, 1)     15
(2, 2, 0)     16
(2, 2, 1)     17
(3, 0, 0)     18
(3, 0, 1)     19
(3, 1, 0)     20
(3, 1, 1)     21
(3, 2, 0)     22
(3, 2, 1)     23
```



In [ ]:
a = np.arange(0, 24).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
a[(0,0,0)]

0

In [ ]:
a[(0,0,1)]

1

In [ ]:
print('index\t\telement')
for i in np.ndindex(a.shape):
  print(f'{i} {a[i]:7d}')

index		element
(0, 0, 0)       0
(0, 0, 1)       1
(0, 1, 0)       2
(0, 1, 1)       3
(0, 2, 0)       4
(0, 2, 1)       5
(1, 0, 0)       6
(1, 0, 1)       7
(1, 1, 0)       8
(1, 1, 1)       9
(1, 2, 0)      10
(1, 2, 1)      11
(2, 0, 0)      12
(2, 0, 1)      13
(2, 1, 0)      14
(2, 1, 1)      15
(2, 2, 0)      16
(2, 2, 1)      17
(3, 0, 0)      18
(3, 0, 1)      19
(3, 1, 0)      20
(3, 1, 1)      21
(3, 2, 0)      22
(3, 2, 1)      23


4. 문제3의 배열을 concatenate() 함수를 사용하여 다음과 같은 배열을 만드세요.


```
1) array([0, 1, 6, 7])
2) array([ 0,  1, 14, 15])
3)
array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])
4)
array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])
```




In [ ]:
a = np.arange(0, 24).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
np.concatenate((a[0,0], a[1,0]),axis=0)

array([0, 1, 6, 7])

In [ ]:
np.concatenate((a[0,0], a[2,1]),axis=0)

array([ 0,  1, 14, 15])

In [ ]:
np.concatenate((a[0], a[1]),axis=0)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.concatenate((a[0], a[1]),axis=1)

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

# 수학,통계 함수

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.sum(a)

4

In [ ]:
np.sum(a, axis=0)  # 열끼리 더함

array([5, 7, 9])

In [ ]:
np.sum(a, axis=1)  # 행끼리 더함

array([ 6, 15])

In [ ]:
np.min(a)  

1

In [ ]:
np.argmin(a)  # 최솟값의 인덱스

0

In [ ]:
np.argmax(a)  # 최댓값의 인덱스

5

In [ ]:
np.mean(a, axis = 1)  # 행끼리 평균

array([2., 5.])

In [ ]:
a.std()

1.707825127659933

In [ ]:
a.std(axis=0)

array([1.5, 1.5, 1.5])

In [ ]:
a.var(axis=0)

array([2.25, 2.25, 2.25])

# 선형방정식 풀이

In [ ]:
a = np.array([[2,3],[1,-2]])
b = np.array([1,4])
x = np.linalg.solve(a,b)  # 연립방정식 해 구하기
x

array([ 2., -1.])